### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by josenaves** [Ethereum-BR/FAQ#1]
O que é blockchain?

**Comment by mcreimer** [comment]
Blockchain é uma tecnologia que compreende uma cadeia de blocos de transações enviadas por clientes em uma rede peer-to-peer, de forma descentralizada.
Ele garante imutabilidade nas transações confirmadas, transparência e alta segurança através de técnicas de hash e criptografia.  Protocolos de consenso são utilizados para garantir apenas a entrada de blocos corretos na cadeia.
O blockchain pode ser permissionado ou não-permissionado.  O primeiro é relativo a uma rede privada, onde é necessária autorização para participar; já o segundo roda em uma rede pública onde qualquer um pode fazer parte.
Eles permitem a criação de criptomoedas e tokens.
Os blockchains mais difiundidos atualmente são o Ethereum e Hyperledger Fabric
