### ISSUE TITLE
Ethereum

### ISSUE THREAD

**Issue by josenaves** [Ethereum-BR/FAQ#2]
O que é Ethereum?

**Comment by mcreimer** [comment]
Ethereum é uma plataforma blockchain criada por Vitalik Buterin em 2.014.  
Como principal vantagem ao blockchain original do Bitcoin, o Ethereum adicionou os "smart contracts", fornecendo mais inteligência à rede.  Estes contratos são códigos escritos em uma linguagem específica que estabelece regras para certas transações na rede.
A EVM (Ethereum Virtual Machine) é considerada Turing completude, pois permite ser programada como um computador pradrão.
É uma rede pública que utiliza PoW (Proof of Work) como protocolo de consenso e usa o recurso da mineração dos blocos para garantir a segurança da rede e a geração da moeda da rede, o Ether.
Para a execução de smart contracts na rede é necessário pagamento, calculado em gas de acordo com a complexidade do mesmo, e convertido para Ethers.
Solidity é a linguagem mais difundida para a codificação de smart contracts.
